//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FORUM_WEB.Models.FrameWork
{
    using System;
    using System.Collections.Generic;
    
    public partial class BinhLuan
    {
        public int ID_BinhLuan { get; set; }
        public Nullable<int> ID_BaiDang { get; set; }
        public string NoiDung { get; set; }
        public Nullable<System.DateTime> NgayBinhLuan { get; set; }
        public string TenDangNhap { get; set; }
    
        public virtual BaiDang BaiDang { get; set; }
        public virtual TaiKhoan TaiKhoan { get; set; }
    }
}
